--
-- Script was generated by Devart dbForge Studio 2021 for SQL Server, Version 6.0.470.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 08.06.2022 11:42:46
-- Server version: 13.00.4001
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('18187cac-6212-460d-be04-0001d8d3ab49', 'I84.9. Геморрой без осложнения неуточненный', 'I84.9')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('35c49e11-52a7-4039-bb22-00059f38f8a7', 'E16.8. Другие уточненные нарушения внутренней секреции поджелудочной железы', 'E16.8')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('2d2f5cc5-ec08-4a1a-a70e-0009dd1a50fa', 'V15.9. Велосипедист без дополнительных уточнений, пострадавший в результате дорожного несчастного случая при столкновении с поездом или другим железнодорожным транспортным средством', 'V15.9')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('e8b48e92-7f35-483e-bda3-000a686a6e87', 'M42. Остеохондроз позвоночника', 'M42')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('3e8a524b-67a8-4b4a-be21-0011859ed04b', 'C20. Злокачественное новообразование прямой кишки', 'C20')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('beb9b9a3-818c-4028-8198-001460297966', 'C16.0. Злокачественное новообразование кардии', 'C16.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('9ae05b35-00a3-4309-b6a0-0017e5f62574', 'N15. Другие тубулоинтерстициальные болезни почек', 'N15')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('9fe0f768-93b6-46f8-950e-001a81e42b18', 'G51. Поражения лицевого нерва', 'G51')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('d68c7c7d-1d9c-4146-90a2-001d633a0bbb', 'W31.1. Соприкосновение с другими и неуточненными механизмами. В специальном учреждении для проживания', 'W31.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('fa0e890c-d205-46c0-87e3-001dafa180f6', 'C72. Злокачественное новообразование спинного мозга, черепных нервов и других отделов центральной нервной системы', 'C72')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('8cbc3cd1-c73b-4b51-b7f7-0027df2a58d9', 'A36.1. Дифтерия носоглотки', 'A36.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('aeb7e859-d6d4-4334-ac6c-0028f5ab69f5', 'X08.5. Воздействие других уточненных источников дыма, огня и пламени. В учреждении и районе торговли и обслуживания', 'X08.5')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('14d81999-f63f-4188-a83c-002a27c7f6c6', 'F17.0. Психические и поведенческие расстройства, вызванные употреблением табака. Острая интоксикация', 'F17.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('f357e44e-21ee-4736-af82-002a32f71fa3', 'E86. Уменьшение объема жидкости', 'E86')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('15b655df-43dc-4d0d-a321-002bfd19dd92', 'E04.0. Нетоксический диффузный зоб', 'E04.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('a3dc0fc9-3b56-458b-94d9-002cb1784e63', 'G03.1. Хронический менингит', 'G03.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('9be2eb22-885b-4e8a-8be4-00320f064b22', 'H51.8. Другие уточненные нарушения содружественного движения глаз', 'H51.8')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('6edc0b8f-0e57-48e1-9553-0035e1a9af85', 'B47. Мицетома', 'B47')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('3bf64271-3069-45e9-a521-0039dc0c1d50', 'Q77.7. Спондилоэпифизарная дисплазия', 'Q77.7')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('8aa12280-30cf-455e-81ae-0042375e6262', 'Q12.3. Врожденная афакия', 'Q12.3')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('cc2066cb-c5a6-4af2-835c-0043bd812fc9', 'T34.6. Отморожение с некрозом тканей в тазобедренной области и бедра', 'T34.6')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('86036163-b39f-4654-aca2-0045e4b9f08a', 'P94.0. Преходящая тяжелая миастения новорожденного', 'P94.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('9b86c205-b367-4180-9822-0046d833eb59', 'F50. Расстройства приема пищи', 'F50')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('492ed423-fe03-4fee-ab4f-0047da001cd8', 'T06.0. Травмы головного мозга и черепных нервов в сочетании с травмами спинного мозга и других нервов на уровне шеи', 'T06.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('8bdd1e23-23fc-4f7a-825b-004948a088cf', 'W80.8. Вдыхание и заглатывание другого инородного тела, приводящее к закупорке дыхательных путей. В других уточненных местах', 'W80.8')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('a41e6d4b-4a03-4c06-93d3-0049678ee205', 'P13.8. Повреждения других частей скелета при родовой травме', 'P13.8')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('9aba1385-7a08-46c5-8fd4-0049a52d7428', 'B25.1. Цитомегаловирусный гепатит (K77.0*)', 'B25.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('1468f250-3726-4343-8f64-0050ba02051b', 'S84.1. Травма малоберцового нерва на уровне голени', 'S84.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('8de16a02-79c6-443a-98d0-0052fb10b561', 'K60.0. Острая трещина заднего прохода', 'K60.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('8731cb38-49d2-47a1-9851-00560c4cb3db', 'E66.2. Крайняя степень ожирения, сопровождаемая альвеолярной гиповентиляцией', 'E66.2')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('e3a1d4dd-eb01-4955-9813-00566cbd3ce8', 'S02.10. Перелом основания черепа закрытый', 'S02.10')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('f0639b22-5074-4c4f-ad0c-00661dcba882', 'K82.1. Водянка желчного пузыря', 'K82.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('3cfffa60-4e72-4201-a24f-006827fe000d', 'M81.3. Постхирургический остеопороз, вызванный нарушением всасывания', 'M81.3')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('32353000-a16b-4ec4-8378-006965c23a6e', 'S92.10. Перелом таранной кости закрытый', 'S92.10')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('ca327cd7-4637-46f0-af71-0069690afed4', 'V84.7. Лицо, находившееся вне специального транспортного средства, используемого в сельском хозяйстве, пострадавшее в результате недорожного несчастного случая', 'V84.7')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('0169d394-2af2-440e-8d03-00714b664fed', 'V13.0. Велосипедист-водитель, пострадавший в результате недорожного несчастного случая при столкновении с легковым автомобилем, грузовым автомобилем типа пикап или фургоном', 'V13.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('8745eb2a-7d7f-422a-9a50-007676302da7', 'T17.1. Инородное тело в носовом ходе', 'T17.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('ba0c80c5-8bc1-4b04-b1aa-007833e76609', 'C94.0. Острый эритроидный лейкоз', 'C94.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('83eb28ff-c775-4b8e-9857-00828f4afce0', 'M20.1. Наружное искривление большого пальца [hallus valguss] (приобретенное)', 'M20.1')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('5613a959-06a0-4851-ae92-0082cc37f3eb', 'T06.4. Травмы мышц и сухожилий с вовлечением нескольких областей тела', 'T06.4')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('d562dc42-602b-4d17-a0af-0083da1370c0', 'Y90.8. Содержание алкоголя в крови 240 мг/100 мл или более', 'Y90.8')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('096b36e9-1b50-4822-ab14-0085141adfe9', 'V17. Велосипедист, пострадавший при столкновении с закрепленным или стационарным объектом', 'V17')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('015a4f86-ada2-4846-b245-00880188cf4f', 'H50.4. Другие и неуточненные гетеротропии', 'H50.4')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('ac80af2b-4d05-4be9-8a2f-0089c033b3db', 'O72.0. Кровотечение в третьем периоде родов', 'O72.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('19d6d8f7-abc8-4713-b57c-009145afbc37', 'O10.2. Существовавшая ранее почечная гипертензия, осложняющая беременность, роды и послеродовой период', 'O10.2')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('dfecc035-9cbb-4836-9b8f-00929798e1f9', 'Q96.3. Мозаицизм 45,X/46,XX или XY', 'Q96.3')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('a2209950-c5bd-4643-9dd4-0092f1b61b6c', 'F12.0. Психические и поведенческие расстройства, вызванные употреблением каннабиоидов. Острая интоксикация', 'F12.0')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('d800f048-18ef-4b2e-ab0b-00935cd3eaa0', 'T38.3. Отравление инсулином и пероральными гипогликемическими [противодиабетическими] препаратами', 'T38.3')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('78551cbd-79fd-4d84-baaf-00997c94db78', 'C91.4. Волосатоклеточный лейкоз', 'C91.4')
INSERT MIS_DIP.dbo.DIAGNOSIS(ID_Diagnoz, Title, KOD_MKB) VALUES ('0ef97d5e-9fd2-43c4-b89f-009cf546f4ad', 'J35.9. Хроническая болезнь миндалин и аденоидов неуточненная', 'J35.9')
GO